"use strict";
// Generated by tools/build_engine.py from app.js. No DOM access; snapshot adapter only.
let DB,ownedDrift,manualDrift,armorSettings,skillLimits,excluded,armorSlotCache,config,theoryCandidateCache=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const $=id=>config.values[id]||{value:"",checked:false};
const document={querySelectorAll:()=>config.driftPool.map(value=>({value}))};
function nextPaint(){return new Promise(resolve=>setTimeout(resolve,0))}

const SLOT_ORDER=["head","chest","arms","waist","legs"];
const SLOT_JA={head:"頭",chest:"胴",arms:"腕",waist:"腰",legs:"脚"};
const SEARCH_BEAM_LIMIT=2600;
const SEARCH_FINAL_LIMIT=120;
const SEARCH_POWER_SLOT_LIMIT=22;
const SEARCH_SKILL_SLOT_LIMIT=34;
const MODELED_POWER_SKILLS=["攻撃活性","果敢","力任せ","攻撃","攻撃・境地","見切り","弱点特効","力の解放","グループハント強化【攻撃】","連撃","攻めの守勢","火事場力","超会心","会心撃【属性】","滅尽龍の渇望","闘気活性","ジャスト巧撃【持続】","闇討ち"];
const MODEL_VERSION="generic-0.6-rc2-r1";
function maxLv(name){return DB.skills[name]?.max??5}
function lv(tbl,l){return l>0?(tbl[Math.min(l,tbl.length)-1]??tbl[tbl.length-1]??0):0}
function getUptime(id){const e=$("up_"+id);return e?+e.value/100:0}
function elementSkill(el){return ["火","水","雷","氷","龍"].includes(el)?`${el}属性攻撃強化`:null}
function elementAdvanced(el){return ["火","水","雷","氷","龍"].includes(el)?`${el}属性攻撃強化・境地`:null}
function sumSkills(parts,weaponSkills={},drift={}){
 const s={};
 for(const src of [weaponSkills,...parts.map(x=>x.skills||{}),drift]){
  for(const [k,v] of Object.entries(src||{})) s[k]=(s[k]||0)+(+v||0);
 }
 for(const k of Object.keys(s))s[k]=Math.min(s[k],maxLv(k));
 return s;
}
function calcFromSkills(skills,weapon,statBonus={}){
 let raw=(+weapon.attack||0)+(+statBonus.attack||0), aff=(+weapon.affinity||0)+(+statBonus.affinity||0), elem=+weapon.elementValue||0;
 const baseAff=aff, b=[];
 if(+statBonus.attack)b.push(["漂移付加・攻撃力",`攻撃 +${+statBonus.attack}`]);if(+statBonus.affinity)b.push(["漂移付加・会心率",`会心 +${+statBonus.affinity}%`]);
 const atk=lv([50,100,150,200,300],skills["攻撃"]||0); if(atk){raw+=atk;b.push(["攻撃",`攻撃 +${atk}`])}
 if((skills["攻撃"]||0)>=5){const v=lv([150,350],skills["攻撃・境地"]||0);if(v){raw+=v;b.push(["攻撃・境地",`攻撃 +${v}`])}}

 const reckless=skills["力任せ"]||0;if(reckless){const attack=lv([100,200,300,400,500],reckless),penalty=lv([5,10,15,20,30],reckless);raw+=attack;aff-=penalty;b.push(["力任せ",`攻撃 +${attack} / 会心 -${penalty}%`])}
 const ce=lv([10,15,20,30,40],skills["見切り"]||0);if(ce){aff+=ce;b.push(["見切り",`会心 +${ce}%`])}
 const wex=lv([20,25,30,40,50],skills["弱点特効"]||0)*getUptime("wex");if(wex){aff+=wex;b.push(["弱点特効",`平均会心 +${wex.toFixed(1)}%`])}
 const latent=lv([20,30,40,50,60],skills["力の解放"]||0)*getUptime("latent");if(latent){aff+=latent;b.push(["力の解放",`平均会心 +${latent.toFixed(1)}%`])}

 if(skills["グループハント強化【攻撃】"] && $("groupHunt").checked){const v=80*skills["グループハント強化【攻撃】"];raw+=v;b.push(["グループハント強化【攻撃】",`グループ狩猟: 攻撃 +${v}`])}

 const elemName=elementSkill(weapon.element);
 if(elemName){const add=lv([50,100,200,350,500],skills[elemName]||0);if(add){elem+=add;b.push([elemName,`属性 +${add}`])}}
 const advName=elementAdvanced(weapon.element);
 if(advName && (skills[elemName]||0)>=5){const add=lv([200,400],skills[advName]||0);if(add){elem+=add;b.push([advName,`属性 +${add}`])}}


 const powerhouse=lv([.10,.15,.25],skills["攻撃活性"]||0);if(powerhouse){raw*=1+powerhouse;b.push(["攻撃活性",`物理 ×${1+powerhouse}`])}
 const burst=lv([.05,.10,.15,.20,.30],skills["連撃"]||0)*getUptime("burst");if(burst){raw*=1+burst;b.push(["連撃",`平均物理 ×${(1+burst).toFixed(3)}`])}
 const guard=lv([.10,.15,.20,.30,.40],skills["攻めの守勢"]||0)*getUptime("guard");if(guard){raw*=1+guard;b.push(["攻めの守勢",`平均物理 ×${(1+guard).toFixed(3)}`])}
 const hero=lv([.10,.20,.30,.40,.50],skills["火事場力"]||0)*getUptime("heroics");if(hero){raw*=1+hero;b.push(["火事場力",`平均物理 ×${(1+hero).toFixed(3)}`])}

 const critBoost=skills["超会心"]?lv([1.30,1.35,1.40,1.45,1.50],skills["超会心"]):1.25;
 // Integrate conditional affinity before clamping: average-then-clamp biases caps/negative affinity.
 const wexFull=lv([20,25,30,40,50],skills["弱点特効"]||0),latentFull=lv([20,30,40,50,60],skills["力の解放"]||0);
 const wp=getUptime("wex"),lp=getUptime("latent"),fixed=aff-wexFull*wp-latentFull*lp;
 let critMul=0,posCrit=0,effAff=0;
 for(const [onW,pw] of [[0,1-wp],[1,wp]])for(const [onL,pl] of [[0,1-lp],[1,lp]]){const probability=pw*pl,a=clamp(fixed+onW*wexFull+onL*latentFull,-100,100);effAff+=probability*a;critMul+=probability*(a>=0?1+a/100*(critBoost-1):1+(-a)/100*(.75-1));posCrit+=probability*Math.max(0,a)/100}
 let rawExp=raw*critMul;b.push(["会心期待値",`${effAff.toFixed(1)}% / 倍率 ${critBoost.toFixed(2)} → ×${critMul.toFixed(4)}`]);
 // Generic damage: critical affects elemental damage; critical-element increase applies to weapon element only.
 const inc=lv([.30,.40,.50,.60,.80],skills["会心撃【属性】"]||0);
 elem=elem*critMul+(+weapon.elementValue||0)*inc*posCrit*critBoost;
 if(inc)b.push(["会心撃【属性】",`武器属性値のみ +${(inc*100).toFixed(0)}%（会心時）`]);

 const nerg=lv([.10,.15,.20],skills["滅尽龍の渇望"]||0);if(nerg){rawExp*=1+nerg;elem*=1+nerg;b.push(["滅尽龍の渇望",`ダメージ ×${(1+nerg).toFixed(2)}`])}
 const fs=lv([.10,.15,.20,.25,.35],skills["闘気活性"]||0)*getUptime("spirit");if(fs){rawExp*=1+fs;elem*=1+fs;b.push(["闘気活性",`平均ダメージ ×${(1+fs).toFixed(3)}`])}
 const daring=lv([.05,.10,.20],skills["果敢"]||0);if(daring){rawExp*=1+daring;elem*=1+daring;b.push(["果敢",`ダメージ ×${1+daring} / ジャスト回避不可`])}
 if(daring&&skills["ジャスト巧撃【持続】"])b.push(["発動制約","果敢によりジャスト巧撃【持続】は発動不可（加点0）"]);
 const od=(daring?0:1)*lv([.10,.15,.20,.25,.35],skills["ジャスト巧撃【持続】"]||0)*getUptime("dodger");if(od){rawExp*=1+od;elem*=1+od;b.push(["ジャスト巧撃【持続】",`平均ダメージ ×${(1+od).toFixed(3)}`])}
 const sn=lv([.10,.15,.20,.25,.30],skills["闇討ち"]||0)*getUptime("sneak");if(sn){rawExp*=1+sn;elem*=1+sn;b.push(["闇討ち",`平均ダメージ ×${(1+sn).toFixed(3)}`])}

 const useElem=$("weakElement").checked && !["無属性","毒","麻痺","睡眠","爆破"].includes(weapon.element);
 const elemExp=useElem?elem:0;
 return {score:rawExp+elemExp,rawExpected:rawExp,elemExpected:elemExp,affinity:effAff,breakdown:b};
}
function relevantSkills(req,weapon,limits=skillLimits){
 const set=new Set([...MODELED_POWER_SKILLS,...Object.keys(req||{}),...Object.keys(limits||{}),...Object.keys(weapon.skills||{})]);
 const es=elementSkill(weapon.element),ea=elementAdvanced(weapon.element);if(es)set.add(es);if(ea)set.add(ea);
 if($("driftMode").value==="theory")for(const k of theoreticalCandidateSkills(weapon,req,limits))set.add(k);
 return [...set].filter(k=>DB.skills[k]||Object.prototype.hasOwnProperty.call(req||{},k)||Object.prototype.hasOwnProperty.call(limits||{},k)||Object.prototype.hasOwnProperty.call(weapon.skills||{},k));
}
function stateKey(skills,rel,slots,parts=[]){const mode=$("driftMode").value,tail=mode==="owned"?"#"+parts.map(p=>p.id).join("|"):"";return rel.map(k=>Math.min(skills[k]||0,maxLv(k))).join(",")+"#"+Math.min(slots,10)+tail}
function reqDeficit(skills,req){let d=0;for(const [k,v] of Object.entries(req||{}))d+=Math.max(0,v-(skills[k]||0));return d}
function reqProgress(skills,req){let p=0;for(const [k,v] of Object.entries(req||{}))p+=Math.min(v,skills[k]||0);return p}
function limitsMet(skills,limits=skillLimits){for(const [k,v] of Object.entries(limits||{}))if((skills[k]||0)>v)return false;return true}
function driftableSkill(k){return DB.skills[k]?.drift===true || (Array.isArray(DB.skills[k]?.driftStones)&&DB.skills[k].driftStones.length>0)}
function theoreticalCandidateSkills(weapon,req={},limits=skillLimits){
 if(theoryCandidateCache)return theoryCandidateCache;
 const base=sumSkills([],weapon.skills,{}),must=Object.keys(req||{}).filter(driftableSkill),selected=selectedDriftCandidates(weapon);
 const all=Object.keys(DB.skills).filter(k=>driftableSkill(k)&&(DB.skills[k]?.fire||must.includes(k)||selected.includes(k)));
 const es=elementSkill(weapon.element);if(es&&driftableSkill(es))all.push(es);
 const uniq=[...new Set([...must,...selected,...all])].filter(k=>!Object.prototype.hasOwnProperty.call(limits||{},k)||(base[k]||0)<limits[k]),baseScore=calcFromSkills(base,weapon).score;
 const scored=uniq.map(k=>{const s=combine(base,{[k]:1});return {k,q:calcFromSkills(s,weapon).score-baseScore+(must.includes(k)?1e7:0)+(selected.includes(k)?1e5:0)}}).sort((a,b)=>b.q-a.q);
 return theoryCandidateCache=scored.slice(0,12).map(x=>x.k);
}
function aggregateDrift(byArmor){const out={};for(const arr of Object.values(byArmor||{}))for(const r of arr||[])out[r.skill]=(out[r.skill]||0)+(r.level||1);return out}
function ownedForArmor(id){const x=ownedDrift[id];return Array.isArray(x)?x:[]}
function comboOptions(items,maxPick){const out=[[]];function rec(start,cur){if(cur.length>=maxPick)return;for(let i=start;i<items.length;i++){cur.push(items[i]);out.push([...cur]);rec(i+1,cur);cur.pop()}}rec(0,[]);return out}
function candidateOwnedRecords(part,weapon,req,base){
 const seen=new Set();return ownedForArmor(part.id).filter(r=>r&&r.id&&r.skill&&!seen.has(r.id)&&(seen.add(r.id),true)).slice(0,20);
}
function optimizeDrift(parts,base,weapon,req,mode,limits=skillLimits){
 let states=[{skills:base,byArmor:{},bonus:{attack:0,affinity:0,defense:0},q:calcFromSkills(base,weapon).score}];
 const rel=relevantSkills(req,weapon);
 const theory=mode==="theory"?theoreticalCandidateSkills(weapon,req,limits):[];
 for(const part of parts){
  const slots=availableDriftSlots(part);if(!slots)continue;
  let items=[];
  if(mode==="theory")items=theory.flatMap(k=>Array.from({length:slots},(_,i)=>({id:`theory:${part.id}:${k}:${i}`,skill:k,level:1,attack:0,affinity:0,defense:0,stone:(DB.skills[k]?.driftStones||[]).join(" / ")})));
  else items=candidateOwnedRecords(part,weapon,req,base);
  const options=comboOptions(items,Math.min(slots,3)),map=new Map();
  for(const st of states){for(const opt of options){let add={};for(const r of opt)add[r.skill]=(add[r.skill]||0)+(r.level||1);const skills=combine(st.skills,add);if(!limitsMet(skills,limits))continue;const bonus={attack:st.bonus.attack,affinity:st.bonus.affinity,defense:st.bonus.defense};for(const r of opt){bonus.attack+=+r.attack||0;bonus.affinity+=+r.affinity||0;bonus.defense+=+r.defense||0}const byArmor={...st.byArmor};if(opt.length)byArmor[part.id]=opt.map(x=>({...x}));const score=calcFromSkills(skills,weapon,bonus).score,def=reqDeficit(skills,req),q=score-def*1e7;const key=rel.map(k=>skills[k]||0).join(",")+`#${bonus.attack}#${bonus.affinity.toFixed(2)}`;const old=map.get(key);if(!old||q>old.q)map.set(key,{skills,byArmor,bonus,q})}}
  states=[...map.values()].sort((a,b)=>b.q-a.q).slice(0,64);
 }
 const valid=states.filter(x=>reqMet(x.skills,req)).sort((a,b)=>calcFromSkills(b.skills,weapon,b.bonus).score-calcFromSkills(a.skills,weapon,a.bonus).score);return valid[0]||null;
}
function assignManualToArmors(parts){
 const byArmor={},capacity=new Map(parts.map(p=>[p.id,availableDriftSlots(p)]));
 for(const [skill,count0] of Object.entries(manualDrift)){let count=+count0||0;if(!driftableSkill(skill))return null;for(const p of parts){while(count>0&&(capacity.get(p.id)||0)>0){const arr=byArmor[p.id]||[];arr.push({id:`manual:${p.id}:${skill}:${arr.length}`,level:1,skill,attack:0,affinity:0,defense:0,stone:"manual"});byArmor[p.id]=arr;capacity.set(p.id,capacity.get(p.id)-1);count--}}if(count>0)return null}
 return byArmor;
}
function currentWeapon(){
 const preset=DB.weapons.find(w=>w.id===$("weaponSelect").value)||DB.weapons[0];
 return {...preset,attack:+$("rawInput").value||0,affinity:+$("affInput").value||0,element:$("elementSelect").value,elementValue:+$("elemInput").value||0};
}
function effectiveArmor(a){const setting=armorSettings[a.id];if(!setting||!a.skillsByGrade)return a;const grades=Object.keys(a.skillsByGrade).map(Number).filter(g=>g<=setting.grade).sort((a,b)=>b-a);if(!grades.length)return null;return {...a,grade:`G${setting.grade}`,skills:a.skillsByGrade[grades[0]]}}
function usable(slot){return (armorSlotCache[slot]||[]).filter(a=>!excluded.has(a.id)).map(effectiveArmor).filter(Boolean)}
function driftSlots(parts){return parts.reduce((n,p)=>n+availableDriftSlots(p),0)}
function armorLocalPriority(p,weapon,req,base,limits=skillLimits){
 const ps=p.skills||{};let reqScore=0;
 for(const [k,v] of Object.entries(req||{}))reqScore+=Math.min(v,ps[k]||0)*10000000;
 const merged=combine(base,ps);if(!limitsMet(merged,limits))return -1e15;const power=calcFromSkills(merged,weapon).score;
 const rows=$("driftMode").value==="owned"&&availableDriftSlots(p)?ownedForArmor(p.id):[];
 const own=Math.max(0,...rows.map(r=>calcFromSkills(combine(merged,{[r.skill]:r.level||1}),weapon,r).score-power+(req[r.skill]?1e7:0)));
 return reqScore+power+availableDriftSlots(p)*25+own;
}
function candidateArmors(slot,weapon,req,base,limits=skillLimits){
 const all=usable(slot).filter(p=>limitsMet(combine(base,p.skills||{}),limits));if(all.length<=SEARCH_SKILL_SLOT_LIMIT)return all;
 const limit=Object.keys(req||{}).length?SEARCH_SKILL_SLOT_LIMIT:SEARCH_POWER_SLOT_LIMIT;
 const scored=all.map(p=>({p,q:armorLocalPriority(p,weapon,req,base,limits)})).sort((a,b)=>b.q-a.q);
 const keep=new Map(scored.slice(0,limit).map(x=>[x.p.id,x.p]));
 if(Object.keys(req||{}).length){
  for(const k of Object.keys(req)){
   let n=0;
   for(const x of scored){if((x.p.skills?.[k]||0)>0){keep.set(x.p.id,x.p);if(++n>=10)break}}
  }
 }
 return [...keep.values()].sort((a,b)=>armorLocalPriority(b,weapon,req,base,limits)-armorLocalPriority(a,weapon,req,base,limits)).slice(0,Math.max(limit,40));
}
function searchPriority(st,weapon,req){
 const target=Object.values(req||{}).reduce((a,b)=>a+(+b||0),0);
 const progress=target?reqProgress(st.skills,req)/target:0;
 const deficit=reqDeficit(st.skills,req);
 return progress*1e9-deficit*1e7+calcFromSkills(st.skills,weapon).score+(st.slots||0)*10;
}
function canMeetAfterDrift(st,req,limits=skillLimits){
 if(!limitsMet(st.skills,limits))return false;if(!Object.keys(req||{}).length)return true;const mode=$("driftMode").value;if(mode==="none")return reqMet(st.skills,req);if(mode==="manual")return true;
 for(const [k,v] of Object.entries(req)){if((st.skills[k]||0)>=v)continue;if(mode!=="owned"&&!driftableSkill(k))return false}return true;
}
function selectedDriftCandidates(weapon){
 const nodes=[...document.querySelectorAll("#driftPool input:checked")].map(x=>x.value);
 return nodes.map(x=>x==="__ELEMENT__"?(elementSkill(weapon.element)||"攻撃"):x).filter((x,i,a)=>x&&driftableSkill(x)&&a.indexOf(x)===i);
}
function combine(base,add){const s={...base};for(const [k,v]of Object.entries(add||{}))s[k]=Math.min((s[k]||0)+v,maxLv(k));return s}
function reqMet(skills,req){for(const [k,v]of Object.entries(req||{}))if((skills[k]||0)<v)return false;return true}
function evaluate(parts,weapon,req={},limits=skillLimits){
 const base=sumSkills(parts,weapon.skills,{}),slots=driftSlots(parts),mode=$("driftMode").value;if(!limitsMet(base,limits))return null;
 if(mode==="none"){if(!reqMet(base,req)||!limitsMet(base,limits))return null;return {...calcFromSkills(base,weapon),skills:base,drift:{},driftByArmor:{},driftStats:{attack:0,affinity:0,defense:0},slots,usedDrift:0}}
 if(mode==="manual"){const byArmor=assignManualToArmors(parts);if(!byArmor)return null;const drift=aggregateDrift(byArmor),skills=combine(base,drift);if(!reqMet(skills,req)||!limitsMet(skills,limits))return null;const c=calcFromSkills(skills,weapon);return {...c,skills,drift,driftByArmor:byArmor,driftStats:{attack:0,affinity:0,defense:0},slots,usedDrift:Object.values(drift).reduce((a,b)=>a+b,0)}}
 const best=optimizeDrift(parts,base,weapon,req,mode,limits);if(!best)return null;const drift=aggregateDrift(best.byArmor),stats=best.bonus;if(!limitsMet(best.skills,limits))return null;const c=calcFromSkills(best.skills,weapon,stats);return {...c,skills:best.skills,drift,driftByArmor:best.byArmor,driftStats:stats,slots,usedDrift:Object.values(drift).reduce((a,b)=>a+b,0)}
}
async function enumerateLocal(req={},progressCb=null){
 theoryCandidateCache=null;const weapon=currentWeapon(),base=sumSkills([],weapon.skills,{});if(!limitsMet(base,skillLimits))return [];const rel=relevantSkills(req,weapon,skillLimits);
 const lists=SLOT_ORDER.map(slot=>candidateArmors(slot,weapon,req,base,skillLimits));if(lists.some(x=>x.length===0))return [];
 let states=[{parts:[],skills:base,slots:0}];
 for(let si=0;si<lists.length;si++){
  const list=lists[si],map=new Map();
  for(const st of states){
   for(const p of list){
    const skills=combine(st.skills,p.skills||{});if(!limitsMet(skills,skillLimits))continue;const slots=st.slots+availableDriftSlots(p),key=stateKey(skills,rel,slots,[...st.parts,p]);
    if(!map.has(key))map.set(key,{parts:[...st.parts,p],skills,slots});
   }
  }
  states=[...map.values()];
  if(states.length>SEARCH_BEAM_LIMIT){states.sort((a,b)=>searchPriority(b,weapon,req)-searchPriority(a,weapon,req));states=states.slice(0,SEARCH_BEAM_LIMIT)}
  if(progressCb)progressCb(`検索中… ${SLOT_JA[SLOT_ORDER[si]]} ${states.length.toLocaleString()}候補`);
  await nextPaint();
 }
 states=states.filter(st=>canMeetAfterDrift(st,req,skillLimits)).sort((a,b)=>searchPriority(b,weapon,req)-searchPriority(a,weapon,req)).slice(0,SEARCH_FINAL_LIMIT);
 const out=[];
 for(let i=0;i<states.length;i++){
  const st=states[i],ev=evaluate(st.parts,weapon,req,skillLimits);if(ev)out.push({parts:st.parts,weapon:{...weapon},modelVersion:MODEL_VERSION,...ev});
  if(i%5===4){if(progressCb)progressCb(`最終評価中… ${i+1}/${states.length}`);await nextPaint()}
 }
 if(progressCb)progressCb(`最終評価中… ${states.length}/${states.length}`);return out;
}
function availableDriftSlots(a){
 const setting=armorSettings[a.id],gs=setting?.unlocks||a.driftUnlockGrades||[],grade=setting?.grade||parseInt(String(a.grade||"").replace("G",""),10)||10;
 return gs.filter(g=>Number.isInteger(g)&&g>=1&&g<=grade).length;
}
function isModeled(k){return MODELED_POWER_SKILLS.includes(k)||["火","水","雷","氷","龍"].some(e=>k===elementSkill(e)||k===elementAdvanced(e))}

function configure(input){
 DB=input.db;ownedDrift=input.ownedDrift||{};manualDrift=input.manualDrift||{};armorSettings=input.armorSettings||{};skillLimits=input.skillLimits||{};excluded=new Set(input.excluded||[]);config=input.config;theoryCandidateCache=null;
 armorSlotCache=Object.fromEntries(SLOT_ORDER.map(slot=>[slot,DB.armors.filter(a=>a.slot===slot)]));
}
globalThis.MHNEngine={configure,enumerate:enumerateLocal,evaluate,sumSkills,calcFromSkills,optimizeDrift,aggregateDrift,availableDriftSlots,comboOptions,limitsMet};
