const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
vm.runInThisContext(fs.readFileSync(__dirname+'/../js/engine.js','utf8'));
const E=globalThis.MHNEngine;let passed=0;
function test(name,fn){fn();passed++;console.log('PASS',name)}
const w={id:'w',name:'test',attack:1000,affinity:0,element:'火',elementValue:200,skills:{'攻撃':1}};
const skills=Object.fromEntries(['攻撃','見切り','超会心','火属性攻撃強化','防御','集中','会心撃【属性】'].map(k=>[k,{max:5,drift:true,driftStones:['fixture'],fire:1}]));
const parts=['head','chest','arms','waist','legs'].map((slot,i)=>({id:'a'+i,name:slot,slot,grade:'G10',skills:{},drift:i===0?2:0,driftUnlockGrades:i===0?[5,8]:[]}));
function input(mode='none',owned={}){return {db:{skills,weapons:[w],armors:parts},ownedDrift:owned,excluded:[],armorSettings:{},manualDrift:{},config:{values:{weaponSelect:{value:'w'},rawInput:{value:1000},affInput:{value:0},elementSelect:{value:'火'},elemInput:{value:200},driftMode:{value:mode},weakElement:{checked:true},groupHunt:{checked:false}},driftPool:['攻撃','見切り']}}}
const rec=(id,skill='攻撃',attack=0)=>({id,skill,level:1,attack,defense:0,affinity:0,stone:'fixture'});
E.configure(input());
test('weapon skill exactly once',()=>{const r=E.evaluate(parts,w);assert.equal(r.skills['攻撃'],1);assert.equal(r.score,1250)});
test('no drift ignores owned',()=>{E.configure(input('none',{a0:[rec('x')]}));assert.equal(E.evaluate(parts,w).usedDrift,0)});
test('negative affinity has 0.75 penalty',()=>assert.equal(E.calcFromSkills({}, {...w,affinity:-100}).rawExpected,750));
test('positive affinity clamp',()=>assert.equal(E.calcFromSkills({}, {...w,affinity:200}).rawExpected,1250));
test('status element not added as raw damage',()=>assert.equal(E.calcFromSkills({}, {...w,element:'毒'}).score,1000));
test('skill caps across all sources',()=>assert.equal(E.sumSkills([{skills:{'攻撃':4}}],{'攻撃':3},{'攻撃':2})['攻撃'],5));
test('unimplemented skill does not invent score',()=>assert.equal(E.calcFromSkills({'集中':5},w).score,E.calcFromSkills({},w).score));
test('locked grade slot not usable',()=>{const a={...parts[0],grade:'G4'};assert.equal(E.availableDriftSlots(a),0);assert.equal(E.availableDriftSlots({...a,grade:'G5'}),1)});
test('unknown unlock does not assume G8',()=>assert.equal(E.availableDriftSlots({...parts[0],driftUnlockGrades:[]}),0));
test('owned tied to armor',()=>{E.configure(input('owned',{other:[rec('x')]}));assert.equal(E.evaluate(parts,w).usedDrift,0)});
test('same result ID cannot be equipped twice',()=>{E.configure(input('owned',{a0:[rec('same'),rec('same')]}));const r=E.evaluate(parts,w);assert.equal(r.usedDrift,1);assert.equal(r.skills['攻撃'],2)});
test('distinct results with same skill can fill two slots',()=>{E.configure(input('owned',{a0:[rec('x'),rec('y')]}));const r=E.evaluate(parts,w);assert.equal(r.usedDrift,2);assert.equal(r.skills['攻撃'],3)});
test('drift attack bonus once',()=>{E.configure(input('owned',{a0:[rec('x','防御',5)]}));const r=E.evaluate(parts,w);assert.equal(r.driftStats.attack,5);assert.equal(r.score,1255)});
test('requested owned skill missing from eligible master allowed',()=>{const i=input('owned',{a0:[rec('x','防御')]});i.db={...i.db,skills:{...skills,'防御':{max:5,drift:false}}};E.configure(i);assert.equal(E.evaluate(parts,w,{'防御':1}).skills['防御'],1)});
test('theoretical drift includes weapon skills',()=>{E.configure(input('theory'));const r=E.evaluate(parts,w,{'攻撃':3});assert(r);assert(r.skills['攻撃']>=3);assert.equal(r.usedDrift,2)});
test('manual assigned to actual armor slots',()=>{const i=input('manual');i.manualDrift={'攻撃':2};E.configure(i);const r=E.evaluate(parts,w);assert.equal(r.driftByArmor.a0.length,2)});
test('force Lv5 verified penalty 30%',()=>{E.configure(input());assert.equal(E.calcFromSkills({'力任せ':5},w).affinity,-30)});
test('elemental critical applies to elemental contribution',()=>{E.configure(input());assert.equal(E.calcFromSkills({}, {...w,affinity:100}).elemExpected,250)});
test('critical element scales base weapon element only',()=>{E.configure(input());assert.equal(E.calcFromSkills({'会心撃【属性】':5,'火属性攻撃強化':5}, {...w,affinity:100}).elemExpected,1075)});
test('conditional affinity clamp before averaging',()=>{const i=input();i.config.values.up_wex={value:50};E.configure(i);assert.equal(E.calcFromSkills({'弱点特効':5},{...w,affinity:90}).affinity,95)});
(async()=>{E.configure(input());const results=await E.enumerate({'攻撃':1});assert.equal(results.length,1);assert.equal(results[0].weapon.id,'w');console.log('PASS requested skill search + weapon snapshot');passed++;const i=input();i.excluded=['a0'];E.configure(i);assert.equal((await E.enumerate()).length,0);console.log('PASS exclusion');passed++;console.log(JSON.stringify({passed}));})().catch(e=>{console.error(e);process.exitCode=1});
