const {chromium}=require('playwright'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),reports=path.join(root,'tests','results');fs.mkdirSync(reports,{recursive:true});
const server=http.createServer((req,res)=>{let f=path.join(root,decodeURIComponent(req.url.split('?')[0]).replace(/^\/lab\//,''));if(f===root||f.endsWith('/'))f=path.join(f,'index.html');try{res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.json')?'application/json':f.endsWith('.html')?'text/html':f.endsWith('.webmanifest')?'application/manifest+json':'application/octet-stream');res.end(fs.readFileSync(f))}catch(e){res.statusCode=404;res.end('not found')}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/lab/`;const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});const context=await browser.newContext({viewport:{width:820,height:1180},hasTouch:true,acceptDownloads:true});const page=await context.newPage();page.setDefaultTimeout(15000);let errors=[],results=[],dialogs=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>{dialogs.push(d.message());return d.type()==='prompt'?d.accept('RC2 test'):d.accept()});
async function check(name,fn){const start=Date.now();await fn();results.push({name,ms:Date.now()-start,status:'PASS'});console.log('PASS',name,Date.now()-start)}
try{
await check('B01 actual UI malformed nested import is atomic',async()=>{await page.goto(url);await page.waitForFunction(()=>document.querySelector('#covWeapons').textContent==='721');await page.evaluate(()=>persist());const before=await page.evaluate(()=>({bytes:localStorage.getItem('mhnbl_v06_snapshot'),html:document.querySelector('#mysetsGrid').innerHTML}));const o=JSON.parse(before.bytes);o.mysets=[{id:'bad',name:'bad',weapon:{name:'test'},parts:[null],skills:{},score:1,created:'2026-09-18'}];await page.locator('#importFile').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(o))});await page.waitForTimeout(100);assert.deepEqual(await page.evaluate(()=>({bytes:localStorage.getItem('mhnbl_v06_snapshot'),html:document.querySelector('#mysetsGrid').innerHTML})),before)});
await check('B02 actual Worker results retain start conditions while UI changes',async()=>{await page.evaluate(()=>{requirements={攻撃:1};armorSettings={};ownedDrift={};});await page.locator('#powerSearch').click();await page.waitForTimeout(100);await page.evaluate(()=>{requirements.攻撃=5;armorSettings[DB.armors[0].id]={grade:4,unlocks:[5,8]};ownedDrift[DB.armors[0].id]=[{id:'new',skill:'攻撃',level:1,attack:3}];});await page.locator('#rawInput').fill('999');await page.locator('#rawInput').dispatchEvent('change');await page.waitForFunction(()=>!document.querySelector('#powerSearch').disabled,{},{timeout:60000});const c=await page.evaluate(()=>lastPower[0].searchConditions);assert.equal(c.requirements.攻撃,undefined);assert.deepEqual(c.armorSettings,{});assert.deepEqual(c.ownedDrift,{});assert.notEqual(c.weapon.attack,999);assert.notEqual(c.values.rawInput.value,'999')});
await check('B03 quota failure visible; pending set exports then retries',async()=>{await page.evaluate(()=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('fixture quota','QuotaExceededError')}});await page.locator('#powerResults .result').first().click();await page.locator('#saveDetail').click();assert(!dialogs.includes('マイセットに登録しました。'));assert.match(await page.locator('#storageNotice').textContent(),/未保存/);await page.locator('#modalClose').click();const downloaded=page.waitForEvent('download');await page.locator('#exportPending').click();const file=await (await downloaded).path();const backup=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(backup.mysets.length,1);await page.evaluate(()=>Storage.prototype.setItem=window.originalSetItem);await page.locator('#retrySave').click();assert.equal(await page.locator('#storageNotice').isVisible(),false);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('mhnbl_v06_snapshot')).mysets.length),1)});
await check('B01 corrupt startup recovery keeps bytes and exports original',async()=>{await page.evaluate(()=>localStorage.setItem('mhnbl_v06_snapshot','{broken-original'));await page.reload();await page.waitForFunction(()=>document.querySelector('#covWeapons').textContent==='721');assert.match(await page.locator('#storageNotice').textContent(),/自動保存を停止/);await page.locator('#rawInput').fill('1234');await page.locator('#rawInput').dispatchEvent('change');assert.equal(await page.evaluate(()=>localStorage.getItem('mhnbl_v06_snapshot')),'{broken-original');const downloaded=page.waitForEvent('download');await page.locator('#exportCorrupt').click();assert.equal(fs.readFileSync(await (await downloaded).path(),'utf8'),'{broken-original')});
await check('B01 valid restore recovers UI and quarantines corrupt original',async()=>{const valid={app:'MH Now Build Lab',schemaVersion:6,excluded:[],mysets:[],requirements:{},manualDrift:{},ownedDrift:{},armorSettings:{}};await page.locator('#importFile').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(valid))});await page.waitForTimeout(100);assert.equal(await page.locator('#storageNotice').isVisible(),false);assert(await page.evaluate(()=>Object.keys(localStorage).some(k=>k.includes('_quarantine_')&&localStorage.getItem(k)==='{broken-original')));assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('mhnbl_v06_snapshot')).schemaVersion),6)});
assert.deepEqual(errors,[]);console.log(JSON.stringify(results));
}finally{fs.writeFileSync(path.join(reports,'rc2-ui-results.json'),JSON.stringify({results,errors},null,2));await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exitCode=1;server.close()});
