const {makeApp,master,root}=require('./app-harness.cjs'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
let count=0;async function check(name,fn){await fn();count++;console.log('PASS',name)}
const clone=x=>JSON.parse(JSON.stringify(x));
const backup=()=>({app:'MH Now Build Lab',schemaVersion:6,excluded:[],mysets:[],requirements:{},manualDrift:{},ownedDrift:{},armorSettings:{}});
const set=()=>({id:'set1',name:'set',weapon:clone(master.weapons[1]),parts:['head','chest','arms','waist','legs'].map(s=>clone(master.armors.find(a=>a.slot===s))),skills:{攻撃:1},score:1000,created:'2026-09-18T00:00:00Z'});
const record={id:'r1',skill:'攻撃',level:1,attack:3,affinity:0,defense:0,stone:'fixture'};
(async()=>{
await check('B01 nested invalid imports preserve exact bytes and memory',async()=>{const a=makeApp(),good=backup();good.mysets=[set()];const bytes=JSON.stringify(good,null,4);a.stored.set('mhnbl_v06_snapshot',bytes);a.run('restoreStartup()');const state=a.run('JSON.stringify(mysets)');const bads=[o=>o.mysets[0].parts=[null],o=>o.mysets[0].weapon=null,o=>o.mysets[0].parts[0].slot='weapon',o=>o.mysets[0].parts[1].id=o.mysets[0].parts[0].id,o=>o.mysets[0].skills={攻撃:'1'},o=>o.mysets[0].score=-2,o=>o.mysets[0].driftByArmor={wrong:[record]},o=>o.mysets[0].stats={attack:'NaN'},o=>o.mysets[0].searchConditions={armorSettings:{a:{grade:11,unlocks:[]}}},o=>o.preferences={values:{rawInput:{value:'infinity'}}},o=>o.schemaVersion=7];for(const change of bads){const bad=clone(good);change(bad);await assert.rejects(a.sandbox.importBackup({text:async()=>JSON.stringify(bad)}));assert.equal(a.stored.get('mhnbl_v06_snapshot'),bytes);assert.equal(a.run('JSON.stringify(mysets)'),state)}});
await check('B01 dangerous keys, excessive depth, nonfinite and duplicate drift rejected',()=>{const a=makeApp();assert.throws(()=>a.sandbox.validateBackup(JSON.parse('{"app":"MH Now Build Lab","__proto__":{}}')));const o=backup();o.requirements={攻撃:Infinity};assert.throws(()=>a.sandbox.validateBackup(o));o.requirements={};o.ownedDrift={a:[record,record]};assert.throws(()=>a.sandbox.validateBackup(o));o.ownedDrift={};let x=o;for(let i=0;i<30;i++){x.child={};x=x.child}assert.throws(()=>a.sandbox.validateBackup(o))});
await check('B01 legacy migration and unknown references preserved',()=>{const a=makeApp(),o=backup();delete o.schemaVersion;o.mysets=[set()];o.mysets[0].parts[0].id='unknown-old-id';o.mysets[0].weapon.id='legacy-weapon';o.ownedDrift={'unknown-old-id':[record]};o.excluded=['unknown-old-id'];const v=a.sandbox.validateBackup(o);assert.equal(v.schemaVersion,6);assert.equal(v.mysets[0].parts[0].referenceStatus,'unknown-reference');assert.equal(v.mysets[0].weapon.id,'legacy-weapon');assert.equal(v.ownedDrift['unknown-old-id'][0].id,'r1');assert.equal(v.excluded[0],'unknown-old-id')});
await check('B01 corrupt startup locks writes without deleting original',()=>{const a=makeApp({'mhnbl_v06_snapshot':'{corrupt'});assert.doesNotThrow(()=>a.run('restoreStartup()'));assert.equal(a.run('recoveryLocked'),true);assert.equal(a.sandbox.persist(),false);assert.equal(a.stored.get('mhnbl_v06_snapshot'),'{corrupt');assert.equal(a.run('corruptSnapshot'),'{corrupt')});
await check('B01 valid recovery quarantines original bytes',async()=>{const a=makeApp({'mhnbl_v06_snapshot':'broken'});a.run('restoreStartup()');for(const fn of ['applyPreferences','renderReq','renderManualDrift','renderSkillCatalog','renderMysets','renderArmorCatalog','renderDriftArmorList','renderDriftEditor','updateStats'])a.sandbox[fn]=()=>{};await a.sandbox.importBackup({text:async()=>JSON.stringify(backup())});assert([...a.stored.entries()].some(([k,v])=>k.includes('quarantine')&&v==='broken'));assert.equal(a.run('recoveryLocked'),false)});
await check('B02 deep immutable snapshot across every mutable search input',async()=>{const a=makeApp();a.run('requirements={攻撃:1};armorSettings={a:{grade:10,unlocks:[5,8]}};manualDrift={攻撃:1};ownedDrift={a:[{id:"x",skill:"攻撃",level:1,attack:3}]};');const promise=a.sandbox.enumerate(a.run('requirements'));const worker=a.worker(),sent=clone(worker.message);a.run('requirements.攻撃=5;armorSettings.a.grade=4;armorSettings.a.unlocks[0]=2;manualDrift.攻撃=3;ownedDrift.a[0].attack=9;DB.version="changed";');a.element('rawInput').value='9000';a.element('weaponSelect').value=master.weapons[1].id;a.element('up_dodger').value='100';worker.onmessage({data:{type:'done',results:[{score:1}],evaluated:1}});const c=(await promise)[0].searchConditions;assert.equal(c.requirements.攻撃,1);assert.equal(c.armorSettings.a.grade,10);assert.equal(c.armorSettings.a.unlocks[0],5);assert.equal(c.manualDrift.攻撃,1);assert.equal(c.ownedDrift.a[0].attack,3);assert.equal(c.weapon.attack,1000);assert.equal(c.weapon.id,'custom');assert.equal(c.values.up_dodger.value,'0');assert.equal(c.masterVersion,sent.input.db.version);assert(Object.isFrozen(c));assert(Object.isFrozen(c.armorSettings.a))});
await check('B02 cancelled worker late responses cannot finish newer search',async()=>{const a=makeApp(),oldPromise=a.sandbox.enumerate(),old=a.worker();const rejection=assert.rejects(oldPromise,/中止/);a.run('activeSearch.cancel()');await rejection;const next=a.sandbox.enumerate(),worker=a.worker();old.onmessage({data:{type:'done',results:[{score:999}],evaluated:1}});old.onerror({message:'old error'});assert.equal(a.run('activeSearch!==null'),true);assert.equal(worker.terminated,undefined);worker.onmessage({data:{type:'done',results:[{score:7}],evaluated:1}});assert.equal((await next)[0].score,7)});
await check('B03 quota failure has no success alert, retry retains pending set',()=>{const a=makeApp();a.deny();const r=set();a.sandbox.saveSet({...r,drift:{},rawExpected:1000,elemExpected:0,affinity:0,slots:0},r.weapon);assert(!a.alerts.includes('マイセットに登録しました。'));assert(a.alerts.some(x=>x.includes('未保存')));assert.equal(a.stored.has('mhnbl_v06_snapshot'),false);assert.equal(a.run('mysets.length'),1);assert.equal(a.run('pendingSave'),true);a.allow();assert.equal(a.sandbox.persist(),true);assert.equal(JSON.parse(a.stored.get('mhnbl_v06_snapshot')).mysets.length,1)});
await check('B03 all changes share unsaved policy; compatibility keys remain read-only',()=>{const a=makeApp({'mhnbl_v02_sets':'[]'});a.denyKeys(/^mhnbl_v02_|^mhnbl_v05_/);assert.equal(a.sandbox.persist(),true);assert.equal(a.stored.get('mhnbl_v02_sets'),'[]');const bytes=a.stored.get('mhnbl_v06_snapshot');a.deny();for(const code of ['excluded.add("old-armor")','ownedDrift={a:[{id:"r",skill:"攻撃",level:1,attack:3}]}','ownedDrift.a[0].attack=4','delete ownedDrift.a','armorSettings={a:{grade:5,unlocks:[5]}}']){a.run(code);assert.equal(a.sandbox.persist(),false);assert.equal(a.stored.get('mhnbl_v06_snapshot'),bytes)}a.allow();assert.equal(a.sandbox.persist(),true);assert.equal(JSON.parse(a.stored.get('mhnbl_v06_snapshot')).armorSettings.a.grade,5)});
const ctx={console,setTimeout};vm.createContext(ctx);vm.runInContext(fs.readFileSync(root+'/js/engine.js','utf8'),ctx);const E=ctx.MHNEngine,w={id:'w',name:'test',attack:1000,affinity:0,element:'火',elementValue:200,skills:{}};E.configure({db:master,config:{values:{weakElement:{checked:true},up_dodger:{value:100}},driftPool:[]}});
await check('B04 powerhouse official 10/15/25%; no duplicate elemental/affinity/bonus',()=>{for(const [lv,m]of [[1,1.10],[2,1.15],[3,1.25]])assert.equal(E.calcFromSkills({攻撃活性:lv},w).score,1000*m+200);const r=E.calcFromSkills({攻撃活性:3},{...w,affinity:20},{attack:4,affinity:5});assert.equal(r.score,(1004*1.25+200)*1.0625)});
await check('B04 daring suppresses impossible dodge buff at every level and uptime',()=>{for(const [lv,m]of [[1,1.05],[2,1.10],[3,1.20]]){const r=E.calcFromSkills({果敢:lv,'ジャスト巧撃【持続】':5},w);assert.equal(r.score,1200*m);assert(r.breakdown.some(x=>x[0]==='発動制約'))}assert.equal(E.calcFromSkills({'ジャスト巧撃【持続】':5},w).score,1620)});
console.log(JSON.stringify({passed:count,environment:'Node VM functions / simulated Worker and storage; not UI'}));
})().catch(e=>{console.error(e);process.exitCode=1});
