const {chromium}=require('playwright'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),reports=path.join(root,'tests','results');fs.mkdirSync(reports,{recursive:true});
const server=http.createServer((req,res)=>{let f=path.join(root,decodeURIComponent(req.url.split('?')[0]).replace(/^\/lab\//,''));if(f===root||f.endsWith('/'))f=path.join(f,'index.html');try{res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.json')?'application/json':f.endsWith('.html')?'text/html':f.endsWith('.webmanifest')?'application/manifest+json':'application/octet-stream');res.end(fs.readFileSync(f))}catch(e){res.statusCode=404;res.end('not found')}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/lab/`;const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});const context=await browser.newContext({viewport:{width:820,height:1180},hasTouch:true,acceptDownloads:true});const page=await context.newPage();let errors=[],results=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.type()==='prompt'?d.accept('RC test'):d.accept());
async function check(name,fn){const start=Date.now();await fn();results.push({name,ms:Date.now()-start,status:'PASS'});console.log('PASS',name,Date.now()-start)}
try{
await check('startup / 721 weapons / 366 armors',async()=>{await page.goto(url);await page.waitForFunction(()=>document.querySelector('#covWeapons').textContent==='721');assert.equal(await page.locator('#covArmors').textContent(),'366')});
await check('bounded weapon list + 14 type filter + attribute + source search',async()=>{await page.locator('#weaponPickerBtn').click();assert((await page.locator('.weapon-row').count())<=80);assert.equal(await page.locator('#weaponTypeFilter option').count(),15);await page.locator('#weaponTypeFilter').selectOption('双剣');await page.locator('#weaponElementFilter').selectOption('火');await page.locator('#weaponSearch').fill('アケノ');await page.waitForTimeout(180);assert.equal(await page.locator('.weapon-row').count(),1);await page.locator('.weapon-row').click();assert.match(await page.locator('#weaponSummary').textContent(),/ロックオン/)});
await check('skill checkbox / partial filter / level / selected only / clear',async()=>{await page.locator('.tab[data-tab=skill]').click();await page.locator('.skill-cat[data-cat=affinity]').click();assert((await page.locator('.skill-row[data-skill=見切り]').count())===1);assert.equal(await page.locator('.skill-row[data-skill=攻撃]').count(),0);await page.locator('.skill-cat[data-cat=all]').click();await page.locator('#skillSearchText').fill('攻撃');await page.waitForTimeout(180);const row=page.locator('.skill-row[data-skill="攻撃"]');await row.locator('.skill-check').check();await page.locator('.skill-row[data-skill="攻撃"] .skill-lv').selectOption('3');await page.locator('#skillSelectedOnly').check();assert.equal(await page.locator('.skill-row').count(),1);await page.locator('#clearReq').click();assert.equal(await page.locator('.skill-row').count(),0);await page.locator('#skillSelectedOnly').uncheck()});
let armorId;
await check('drift manager register / edit / ownership',async()=>{await page.locator('.tab[data-tab=drift]').click();await page.locator('#driftArmorSearch').fill('クルルヘルム');await page.waitForTimeout(180);await page.locator('.drift-armor-row').click();armorId=await page.locator('.drift-armor-row').getAttribute('data-id');await page.locator('#ownedDriftSkillSearch').fill('見切り');await page.locator('input[name=ownedSkill][value="見切り"]').check();await page.locator('#ownedDriftBonusType').selectOption('attack');await page.locator('#ownedDriftBonusValue').fill('3');await page.locator('#addOwnedDrift').click();assert.equal(await page.locator('.drift-owned-item').count(),1);await page.locator('.editOwnedDrift').click();await page.locator('#ownedDriftBonusValue').fill('4');await page.locator('#addOwnedDrift').click();assert.match(await page.locator('.drift-owned-item').textContent(),/攻\+4/)});
await check('no-drift Worker search + result weapon snapshot + save + compare',async()=>{await page.locator('.tab[data-tab=power]').click();await page.locator('#driftMode').selectOption('none');await page.locator('#powerSearch').click();await page.waitForFunction(()=>document.querySelectorAll('#powerResults .result').length>0,{},{timeout:60000});await page.locator('#weaponPickerBtn').click();await page.locator('#weaponCustomBtn').click();await page.locator('#powerResults .result').first().click();assert.match(await page.locator('#modalBody').textContent(),/ロックオン/);assert.match(await page.locator('#modalBody').textContent(),/シルツァリ/);await page.locator('#saveDetail').click();await page.locator('#modalClose').click();await page.locator('#powerResults .cmp').first().click();await page.locator('.tab[data-tab=mysets]').click();assert.equal(await page.locator('#mysetsGrid .set').count(),1);await page.locator('.loadSet').click();await page.locator('.tab[data-tab=compare]').click();assert.equal(await page.locator('#compareGrid .set').count(),1)});
await check('backup roundtrip retains owned / mysets / preferences; malformed import atomic',async()=>{const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('mhnbl_v06_snapshot')));const dl=page.waitForEvent('download');await page.locator('#exportBtn').click();const downloaded=await dl;const file=await downloaded.path();const backup=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(backup.schemaVersion,6);assert.equal(backup.ownedDrift[armorId][0].attack,4);await page.locator('#importFile').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.waitForTimeout(100);const restored=await page.evaluate(()=>JSON.parse(localStorage.getItem('mhnbl_v06_snapshot')));assert.equal(restored.mysets.length,1);assert.equal(restored.ownedDrift[armorId][0].attack,4);const invalid={...backup,ownedDrift:{[armorId]:Array(21).fill(backup.ownedDrift[armorId][0])}};await page.locator('#importFile').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});await page.waitForTimeout(100);assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('mhnbl_v06_snapshot'))),restored)});
await check('materials show unknown quantities including weapon',async()=>{await page.locator('.tab[data-tab=materials]').click();await page.locator('#calcMaterials').click();assert.match(await page.locator('#materialResults').textContent(),/数量未登録/);assert.match(await page.locator('#materialResults').textContent(),/シルツァリ/)});
await check('exclusion persists',async()=>{await page.locator('.tab[data-tab=data]').click();await page.locator('#diagnostics').click();assert.match(await page.locator('#modalBody').textContent(),/漂移候補: 76/);await page.locator('#modalClose').click();await page.locator('#armorSearch').fill('クルルヘルム');await page.locator('.toggleEx').click();assert((await page.evaluate(()=>JSON.parse(localStorage.getItem('mhnbl_v06_snapshot')).excluded)).includes(armorId))});
await check('theory search cancel keeps UI responsive',async()=>{await page.locator('.tab[data-tab=power]').click();await page.locator('#driftMode').selectOption('theory');await page.locator('#powerSearch').click();await page.waitForTimeout(100);await page.locator('#cancelSearch').click();await page.waitForFunction(()=>!document.querySelector('#powerSearch').disabled);assert.match(await page.locator('#powerResults').textContent(),/中止/)});
await check('owned drift search completes',async()=>{await page.locator('#driftMode').selectOption('owned');await page.locator('#powerSearch').click();await page.waitForFunction(()=>document.querySelectorAll('#powerResults .result').length>0,{},{timeout:60000})});
await check('theory full Worker search',async()=>{await page.locator('#driftMode').selectOption('theory');await page.locator('#powerSearch').click();await page.waitForFunction(()=>!document.querySelector('#powerSearch').disabled,{},{timeout:120000});assert((await page.locator('#powerResults .result').count())>0)});
await check('requested skill UI search uses weapon skill',async()=>{await page.locator('#driftMode').selectOption('none');await page.locator('.tab[data-tab=skill]').click();await page.locator('#skillSearchText').fill('ロックオン');await page.waitForTimeout(180);await page.locator('.skill-row[data-skill="ロックオン"] .skill-check').check();await page.locator('#skillSearch').click();await page.waitForFunction(()=>document.querySelectorAll('#skillResults .result').length>0,{},{timeout:60000})});
await check('skill exclusion / max UI applies to final weapon+armor+drift skills',async()=>{await page.locator('.tab[data-tab=skill]').click();await page.locator('#skillSearchText').fill('ロックオン');await page.waitForTimeout(180);let row=page.locator('.skill-row[data-skill="ロックオン"]');await row.locator('.skill-check').check();await row.locator('.skill-mode').selectOption('exclude');await page.locator('#skillSearch').click();await page.waitForFunction(()=>!document.querySelector('#skillSearch').disabled,{},{timeout:60000});assert.equal(await page.locator('#skillResults .result').count(),0);await page.locator('#clearReq').click();await page.locator('#skillSearchText').fill('見切り');await page.waitForTimeout(180);row=page.locator('.skill-row[data-skill="見切り"]');await row.locator('.skill-check').check();await row.locator('.skill-mode').selectOption('max');await row.locator('.skill-lv').selectOption('1');assert.match(await page.locator('#reqList').textContent(),/上限: 見切り Lv1/)});
await check('drift delete',async()=>{await page.locator('.tab[data-tab=drift]').click();await page.locator('#driftArmorSearch').fill('クルルヘルム');await page.waitForTimeout(180);await page.locator('.drift-armor-row').click();await page.locator('.delOwnedDrift').click();assert.equal(await page.locator('.drift-owned-item').count(),0)});
await check('relative-path PWA / offline master / unrelated cache retained',async()=>{await page.evaluate(async()=>{await navigator.serviceWorker.ready;await caches.open('another-app-fixture')});await page.reload();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);await page.reload();await page.waitForFunction(()=>document.querySelector('#covWeapons').textContent==='721');assert((await page.evaluate(()=>caches.keys())).includes('another-app-fixture'));await context.setOffline(false)});
await check('820 / 390 viewport no horizontal overflow',async()=>{for(const width of [820,390]){await page.setViewportSize({width,height:1180});await page.locator(width<=760?'.bottom-tab[data-tab=drift]':'.tab[data-tab=drift]').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(reports,`viewport-${width}.png`),fullPage:true})}});
assert.deepEqual(errors,[]);console.log(JSON.stringify(results));
}finally{fs.writeFileSync(path.join(reports,'ui-results.json'),JSON.stringify({results,errors},null,2));await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exitCode=1;server.close()});
